server:
  port: 80

template:
  resource: classpath:message.mustache

mail:
  recipientMail:
  senderMail:
  server:
    domain:
    port: 587
    username:
    password:

throttling:
  clearExpiredRate: 24h
  ip:
    limit: 5
    window: 24h
  all:
    limit: 15
    window: 24h

spring:
  mail:
    host: ${mail.server.domain:}
    port: ${mail.server.port:587}
    username: ${mail.server.username:}
    password: ${mail.server.password:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${mail.server.domain:}
