server:
  port: 80

template:
  resource: classpath:message.mustache

mail:
  recipientMail: ${MAIL_RECIPIENT_MAIL:}
  senderMail: ${MAIL_SENDER_MAIL:}

throttling:
  clearExpiredRate: ${THROTTLING_CLEAR_EXPIRED_RATE:24h}
  ip:
    limit: ${THROTTLING_IP_LIMIT:5}
    window: ${THROTTLING_IP_WINDOW:24h}
  all:
    limit: ${THROTTLING_ALL_LIMIT:15}
    window: ${THROTTLING_ALL_WINDOW:24h}

spring:
  mail:
    host: ${MAIL_SERVER_DOMAIN:}
    port: ${MAIL_SERVER_PORT:587}
    username: ${MAIL_SERVER_USERNAME:}
    password: ${MAIL_SERVER_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${MAIL_SERVER_DOMAIN:}
